# <center>Vector và Hệ phương trình tuyến tính trong Python</center>

## Mục lục

* [Python và các thư viện tính toán khoa học](#c2)
* [Vector trong Python](#c3)
* [Ma trận (cơ bản) trong Python](#c4)
* [Hệ phương trình tuyến tính và Phép khử Gauss trong Python](#c5)

## Python và các thư viện tính toán khoa học <a class="anchor" id="c2"></a>

[Python](https://www.python.org/) là ngôn ngữ lập trình được dùng phổ biến cho tính toán khoa học (và nhiều mục đích khác). Tài liệu tra cứu chính thống của Python được để ở [Python documentation](https://docs.python.org/3/index.html). Có thể dùng hướng dẫn [The Python Tutorial](https://docs.python.org/3/tutorial/) để học nhanh Python. Có thể dùng sách [Bí kíp luyện Lập trình nhập môn với Python (hBook)](https://github.com/vqhBook/python) để học kĩ Python căn bản. Ngoài ra, có thể dùng một số nguồn tham khảo khác như [Python3 Tutorial](https://www.python-course.eu/python3_course.php), [Numerical Programming with Python](https://www.python-course.eu/numerical_programming_with_python.php), [GeeksforGeeks](https://www.geeksforgeeks.org/python-programming-language/)...

Các thư viện Python phổ biến dùng trong tính toán khoa học là: [NumPy](https://numpy.org/), [SciPy](https://www.scipy.org/), [SymPy](https://www.sympy.org/en/index.html), [pandas](https://pandas.pydata.org/), [scikit-learn](https://scikit-learn.org/stable/), [Matplotlib](https://matplotlib.org/)... Các thư viện này sẽ được giới thiệu, hướng dẫn và dùng trong các buổi Lab, đồ án.

NumPy và SciPy là các thư viện **tính toán số** (numeric computation) giúp tính xấp xỉ nhưng hiệu quả với khối lượng tính toán lớn. Có thể học nhanh NumPy tại [NumPy - the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html).

SymPy là thư viện **tính toán ký hiệu** (symbolic computation) giúp tính chính xác và hình thức với khối lượng tính toán nhỏ. Có thể học nhanh SymPy tại [SymPy Introduction](https://docs.sympy.org/latest/tutorial/intro.html) và [SymPy Matrices](https://docs.sympy.org/latest/tutorial/matrices.html).

Tra cứu các hỗ trợ cho **đại số tuyến tính** (linear algebra) tại:

* [Linear algebra (numpy.linalg)](https://numpy.org/doc/stable/reference/routines.linalg.html#)

* [Linear algebra (scipy.linalg)](https://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg)

* [SymPy Matrices (linear algebra)](https://docs.sympy.org/latest/modules/matrices/matrices.html)

Một số thư viện có dùng trong bài lab này:

* Module [`math`](https://docs.python.org/3/library/math.html) trong thư viện chuẩn Python hỗ trợ các hàm Toán thông dụng.

* Lớp [`fractions.Fraction`](https://docs.python.org/3/library/fractions.html) trong thư viện chuẩn Python hỗ trợ kiểu phân số dùng để tính toán chính xác.

* Các thư viện `numpy`, `scipy`, `sympy`.

* Ngoài ra, hàm `to_fraction` giúp tạo phân số (từ chuỗi, số nguyên, danh sách các số...) khi muốn tính toán chính xác và hàm `myprint` giúp "xuất đẹp" các danh sách (vector, tập vector, ma trận).

In [1]:
import math
from fractions import Fraction
import numpy as np
import scipy.linalg
import sympy
from sympy import Matrix

sympy.init_printing()

# Helper functions
x = ["1/2", "2/3"]
def to_fraction(x):
    if isinstance(x, list):
        return [to_fraction(e) for e in x] # list comprehension
    else:
        return Fraction(x) # "1/2" --> 1/2


    # # Another way to implement this function, without using list comprehension.
    # #     It is a little bit longer!!!
    # if not isinstance(x, list):
    #     return Fraction(x)

    # res = []
    # n = len(x)
    # for i in range(n): # for (i = 0; i < n; i++)
    #     res.append(to_fraction(x[i]))

    # return res
print(to_fraction(x))

y = [[1,2],[3,4]]

def myprint(x, sep=" "):
    if isinstance(x, list) and x:
        if isinstance(x[0], list): # list of list
            m, n = len(x), len(x[0])
            widths = [max(len(str(ai[j])) for ai in x) for j in range(n)]
            rows = [sep.join(format(str(ai[j]), f">{widths[j]}") for j in range(n)) for ai in x]
            print("[" + "\n".join((" [" if i > 0 else "[") + rows[i] + "]" for i in range(m)) + "]")
        else: # list
            print("[" + sep.join(str(e) for e in x) + "]")
    else:
        print(x)

myprint(y)

[Fraction(1, 2), Fraction(2, 3)]
[[1 2]
 [3 4]]


## Vector trong Python <a class="anchor" id="c3"></a>

Một bộ gồm $n$ số thực (n-tuple) $\boldsymbol{v} = (v_1, v_2, ..., v_n) \in \mathbb{R}^n$ được gọi là một **vector** kích thước $n$. Các số $v_1, v_2, ..., v_n \in \mathbb{R}$ được gọi là các **phần tử** (element, entry) của vector. Để phân biệt với vector, các số thực còn được gọi là **vô hướng** (scalar).

Cách đơn giản nhất để biểu diễn vector là dùng **danh sách** (list) các số. Cách hiệu quả và tiện lợi hơn là dùng **NumPy 1D array**.

### Khai báo

In [2]:
# Init
v_list = [1, 2, 3, 4, 5]            # Uses list
v_numpy = np.array([1, 2, 3, 4, 5]) # Uses NumPy

# Display the values
print('Use list: ', v_list)
print('Use NumPy: ', v_numpy)

# Access elements (basic)
print('The first element in vector (list): ', v_list[0])
print('The last element in vector (NumPy): ', v_numpy[-1])

print('Subvector (3 first elements) in vector (list): ', v_list[:3])    # Quick questions: Other ways? What items should come before the colon?
print('Subvector (3 last elements) in vector (NumPy): ', v_numpy[-3:])  # Quick questions: Other ways? What items should come after the colon?

Use list:  [1, 2, 3, 4, 5]
Use NumPy:  [1 2 3 4 5]
The first element in vector (list):  1
The last element in vector (NumPy):  5
Subvector (3 first elements) in vector (list):  [1, 2, 3]
Subvector (3 last elements) in vector (NumPy):  [3 4 5]


Tùy trường hợp, vector $\boldsymbol{v} = (v_1, v_2, ..., v_n) \in \mathbb{R}^n$ có thể được biểu diễn như là **vector dòng** (row vector) hay **vector cột** (column vector)
$$
\boldsymbol{v} =
\begin{bmatrix}
v_1 & v_2 & \cdots & v_n
\end{bmatrix} \in \mathbb{R}^{1 \times n},
$$
$$
\boldsymbol{v} =
\begin{bmatrix}
v_1 \\ v_2 \\ \vdots \\ v_n
\end{bmatrix} \in \mathbb{R}^{n \times 1}.
$$

In [3]:
v_numpy.shape # print(v_numpy.shape)

(5,)

In [4]:
# Uses NumPy
v_row = v_numpy.reshape(1, len(v_numpy))
v_col = v_numpy.reshape(len(v_numpy), 1)

print('Row vector: \n', v_row, '\nShape: ', v_row.shape)
print('\nColumn vector: \n', v_col, '\nShape: ', v_col.shape)

Row vector: 
 [[1 2 3 4 5]] 
Shape:  (1, 5)

Column vector: 
 [[1]
 [2]
 [3]
 [4]
 [5]] 
Shape:  (5, 1)


In [5]:
# Uses SymPy
Matrix([1, 2, 3, 4, 5]) # SymPy treats a vector as a column vector, which is a matrix with only 1 column

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢3⎥
⎢ ⎥
⎢4⎥
⎢ ⎥
⎣5⎦

### Vector không (zero vector)

Vector $\boldsymbol{0} = (0, 0, ..., 0) \in \mathbb{R}^n$ được gọi là **vector không** (zero vector).

2 vector $\boldsymbol{v} = (v_1, v_2, ..., v_n), \boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$ được gọi là **bằng nhau** (equal), kí hiệu $\boldsymbol{v} = \boldsymbol{w}$ nếu $v_i = w_i, \forall i$.

#### Sử dụng list

In [6]:
# Define functions
def is_zero(x):
    # Check if a real number x is equal to 0 (or is very close to 0)
    return math.isclose(x, 0, abs_tol=1e-09)
    # |a - b| <= 0.00000000001 --> a ~ b

def create_zero_vector(n):
    return [0] * n
    # return [0 for _ in range(n)]

def is_zero_vector(v):
    return all(is_zero(vi) for vi in v)
    # If we ignore is_zero function, we can use this code:
    # return v == [0]*len(v)

In [7]:
v = create_zero_vector(3)

# Show value
print(v)

# Check if v is a zero vector
print('Is zero vector: ', is_zero_vector(v))

[0, 0, 0]
Is zero vector:  True


##### TODO: Tìm hiểu thêm

In [8]:
# What is the output when we call: v == 0?
# What is the output when we call: v == create_zero_vector(3)?
# Give explanations

#### Sử dụng NumPy

In [9]:
v = np.zeros(3)

# Show value
print(v)

# Check if v is a zero vector
print('Is zero vector (using built-in function), ', all(v == 0))                # Quick question: What does this code mean: "all(v == 0)"?
print('Is zero vector (using our implemented function): ', is_zero_vector(v))

[0. 0. 0.]
Is zero vector (using built-in function),  True
Is zero vector (using our implemented function):  True


#### Sử dụng SymPy

In [10]:
# TODO: Create a zero vector using SymPy
from sympy.vector import Vector
v = Vector.zero
print(v)


# TODO: Check if a vector is a zero vector using SymPy
is_zero_vector1 = v.is_zero
print(is_zero_vector1)

0
None


### Các phép toán trong Vector

Cho 2 vector $\boldsymbol{v} = (v_1, v_2, ..., v_n), \boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$ và số thực $\alpha \in \mathbb{R}$, ta định nghĩa các phép toán
$$
\boldsymbol{v} + \boldsymbol{w} = (v_1 + w_1, v_2 + w_2, ..., v_n + w_n),
$$
$$
\boldsymbol{v} - \boldsymbol{w} = (v_1 - w_1, v_2 - w_2, ..., v_n - w_n),
$$
$$
\alpha \boldsymbol{v} = (\alpha v_1, \alpha v_2, ..., \alpha v_n).
$$

Cho tập các vector $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k \in \mathbb{R}^n$ và các số $\alpha_1, \alpha_2, ..., \alpha_k \in \mathbb{R}$, ta nói vector
$$
\boldsymbol{w} = \alpha_1 \boldsymbol{v}_1 + \alpha_2 \boldsymbol{v}_2 + ... + \alpha_k \boldsymbol{v}_k
$$

là một **tổ hợp tuyến tính** (linear combination) của $\boldsymbol{v}_1, \boldsymbol{v}_2, ..., \boldsymbol{v}_k$ với các **hệ số** (coefficient) $\alpha_1, \alpha_2, ..., \alpha_k$.

#### Sử dụng List

In [11]:
# Define functions
def add_vector(v, w):
    return [vi + wi for vi, wi in zip(v, w)]

def sub_vector(v, w):
    return [vi - wi for vi, wi in zip(v, w)]

def mul_scalar_vector(alpha, v):
    return [alpha*vi for vi in v]

def equal_vector(v, w):
    return is_zero_vector(sub_vector(v, w)) # 2 vectors are equal if their difference is the zero vector

In [12]:
v = [1, -3, 2]
w = [4, 2, 1]

print('Sum of 2 vectors: ', add_vector(v, w))
print('Subtraction of 2 vectors: ', sub_vector(v, w))
print('Multiplication of vector with scalar (alpha = 2): ', mul_scalar_vector(2, v))
print('Is (v - w) == (v + (-1w))?: ', equal_vector(sub_vector(v, w), add_vector(v, mul_scalar_vector(-1, w))))

Sum of 2 vectors:  [5, -1, 3]
Subtraction of 2 vectors:  [-3, -5, 1]
Multiplication of vector with scalar (alpha = 2):  [2, -6, 4]
Is (v - w) == (v + (-1w))?:  True


#### Sử dụng NumPy

In [13]:
v = np.array(v)
w = np.array(w)

print('Sum of 2 vectors: ', v + w)
print('Subtraction of 2 vectors: ', v - w)
print('Multiplication of vector with scalar (alpha = 2): ', 2*v)
print('Is (v - w) == (v + (-1w))?: ', all((v - w) == (v + (-1*w))))

Sum of 2 vectors:  [ 5 -1  3]
Subtraction of 2 vectors:  [-3 -5  1]
Multiplication of vector with scalar (alpha = 2):  [ 2 -6  4]
Is (v - w) == (v + (-1w))?:  True


#### Sử dụng SymPy

In [14]:
v = Matrix(v)
w = Matrix(w)

print('Sum of 2 vectors: ', v + w)
print('Subtraction of 2 vectors: ', v - w)
print('Multiplication of vector with scalar (alpha = 2): ', 2*v)
print('Is (v - w) == (v + (-1w))?: ', v - w == v + (-1*w)) # Unlike NumPy, SymPy uses "==" operator to compare 2 vectors (matrice)

Sum of 2 vectors:  Matrix([[5], [-1], [3]])
Subtraction of 2 vectors:  Matrix([[-3], [-5], [1]])
Multiplication of vector with scalar (alpha = 2):  Matrix([[2], [-6], [4]])
Is (v - w) == (v + (-1w))?:  True


##### Tổ hợp tuyến tính

In [15]:
print('Linear combination:')
sympy.symbols('alpha')*v + sympy.symbols('beta')*w

Linear combination:


⎡ α + 4⋅β  ⎤
⎢          ⎥
⎢-3⋅α + 2⋅β⎥
⎢          ⎥
⎣ 2⋅α + β  ⎦

### Tích vô hướng

Cho 2 vector $\boldsymbol{v} = (v_1, v_2, ..., v_n), \boldsymbol{w} = (w_1, w_2, ..., w_n) \in \mathbb{R}^n$:

Ta định nghĩa **tích vô hướng** (inner product, dot product) của $\boldsymbol{v}, \boldsymbol{w}$ là
$$
\langle \boldsymbol{v}, \boldsymbol{w} \rangle = v_1w_1 + v_2w_2 + ... + v_n w_n = \sum_{i=1}^n v_i w_i,
$$

In [16]:
def calc_inner_product(v, w):
    return sum(vi*wi for vi, wi in zip(v, w)) # Quick question: What is "zip" function? -> https://docs.python.org/3.10/library/functions.html#zip

In [17]:
v = [1, 2, 3]
w = [4, 5, 2]

print('Inner product of 2 vectors: ', calc_inner_product(v, w))

Inner product of 2 vectors:  20


### Trực giao

Ta nói $\boldsymbol{v}, \boldsymbol{w}$ **trực giao** (orthogonal, perpendicular), kí hiệu $\boldsymbol{v} \bot \boldsymbol{w}$, nếu $\langle \boldsymbol{v}, \boldsymbol{w} \rangle = 0$,

In [18]:
def is_orthogonal(v, w):
    return is_zero(calc_inner_product(v, w))

In [19]:
v = [1, -2, 3]
w = [4, 5, 2]

print(f'Are {v} and {w} orthogonal: ', is_orthogonal(v, w))

Are [1, -2, 3] and [4, 5, 2] orthogonal:  True


### Chuẩn

Ta định nghĩa **chuẩn** (norm, length, magnitude) của $\boldsymbol{v}$ là
$$
\| \boldsymbol{v} \| = \sqrt{\langle \boldsymbol{v}, \boldsymbol{v} \rangle} = \sqrt{v_1^2 + v_2^2 + ... + v_n^2} = \sqrt{\sum_{i=1}^n v_i^2},
$$

In [20]:
def norm_square(v):
    return calc_inner_product(v, v)

def norm(v):
    return sympy.sqrt(norm_square(v)) # Uses SymPy to get sqrt symbol

In [21]:
v = [1, 2, 3]

print(f'Norm of {v}: ')
norm(v)

Norm of [1, 2, 3]: 


√14

### Vector đơn vị

Ta nói $\boldsymbol{v}$ là **vector đơn vị** (unit vector) nếu $\| \boldsymbol{v} \| = 1$,

In [22]:
def is_one(v):
    return math.isclose(v, 1)

def is_unit_vector(v):
    return is_one(norm(v))

In [23]:
one = [1, 0, 0]

print(f'Is {one} a unit vector: ', is_unit_vector(one))

Is [1, 0, 0] a unit vector:  True


### Khoảng cách

Ta định nghĩa **khoảng cách** (distance) giữa $\boldsymbol{v}$ và $\boldsymbol{w}$ là $\| \boldsymbol{v} - \boldsymbol{w} \|$.

In [24]:
def distance(v, w):
    return norm(sub_vector(v, w))

In [25]:
v = [1, -2, 3]
w = [4, 5, 2]

print(f'Distance between {v} and {w}:')
distance(v, w)

Distance between [1, -2, 3] and [4, 5, 2]:


√59

### TODO: Tìm hiểu thêm

Tìm hiểu cách sử dụng NumPy và SymPy cho các khái niệm được liệt kê phía trên (từ Trực giao đến Khoảng cách)

## Ma trận (cơ bản) trong Python <a class="anchor" id="c4"></a>

*(Ma trận sẽ được hướng dẫn kĩ hơn trong Lab 2.)*

### Khái niệm

Một bảng chữ nhật gồm $m$ dòng, $n$ cột các số thực
$$
A =
\begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} \in \mathbb{R}^{m \times n}
$$
được gọi là **ma trận** (matrix) có kích thước (hay có dạng) $m \times n$. Số $a_{ij}$ được gọi là **phần tử** (element, entry) ở dòng $i$, cột $j$ của ma trận $A$.

Ma trận $A \in \mathbb{R}^{m \times n}$ có thể xem như gồm $m$ vector dòng $\mathbb{R}^{1 \times n}$ với dòng $i$ là
$$
\boldsymbol{a}_{i,} =
\begin{bmatrix}
  a_{i1} & a_{i2} & \cdots & a_{in} \\
\end{bmatrix},
$$
hay gồm $n$ vector cột $\mathbb{R}^{m \times 1}$ với cột $j$ là
$$
\boldsymbol{a}_{,j} =
\begin{bmatrix}
  a_{1j} \\ a_{2j} \\ \vdots \\ a_{mj}
\end{bmatrix}.
$$

Ta nói ma trận có được từ $A$ bằng cách xếp các dòng thành các cột là ma trận **chuyển vị** (transpose) của $A$, kí hiệu $A^T$, tức là
$$
A^T =
\begin{bmatrix}
  a_{11} & a_{21} & \cdots & a_{m1} \\
  a_{12} & a_{22} & \cdots & a_{m2} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{1n} & a_{2n} & \cdots & a_{mn}
\end{bmatrix} \in \mathbb{R}^{n \times m}.
$$

Cách đơn giản nhất để biểu diễn ma trận là dùng **danh sách lồng** (nested list) các số. Cách hiệu quả và tiện lợi hơn là dùng **NumPy 2D array**.

### Chuyển vị

#### List

In [26]:
def transpose(A):
    m, n = len(A), len(A[0]) # The size of matrix
    return [[A[i][j] for i in range(m)] for j in range(n)]

A = [[1, 2, 3],
     [4, 5, 6]]

print('Before transposing:')
myprint(A)

print('\nAfter transposing:')
myprint(transpose(A))

Before transposing:
[[1 2 3]
 [4 5 6]]

After transposing:
[[1 4]
 [2 5]
 [3 6]]


#### NumPy

In [27]:
A = np.array(A)

print('Before transposing:')
print(A)

print('\nAfter transposing:')
print(A.T)

Before transposing:
[[1 2 3]
 [4 5 6]]

After transposing:
[[1 4]
 [2 5]
 [3 6]]


#### SymPy

In [28]:
A = Matrix([[sympy.symbols(f"a_{i}{j}") for j in range(1, 4)] for i in range(1, 3)])
A

⎡a₁₁  a₁₂  a₁₃⎤
⎢             ⎥
⎣a₂₁  a₂₂  a₂₃⎦

In [29]:
A.T

⎡a₁₁  a₂₁⎤
⎢        ⎥
⎢a₁₂  a₂₂⎥
⎢        ⎥
⎣a₁₃  a₂₃⎦

### Nhân ma trận với vector

Cho ma trận $A \in \mathbb{R}^{m \times n}$ và vector cột $\boldsymbol{v} \in \mathbb{R}^{n \times 1}$, phép nhân
$$
A\boldsymbol{v} =
\begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
\begin{bmatrix}
  v_1 \\ v_2 \\ \vdots \\ v_n
\end{bmatrix} =
\begin{bmatrix}
  a_{11}v_1 + a_{12}v_2 + ... + a_{1n}v_n \\
  a_{21}v_1 + a_{22}v_2 + ... + a_{2n}v_n \\ \vdots \\
  a_{m1}v_1 + a_{m2}v_2 + ... + a_{mn}v_n \\
\end{bmatrix}
$$
có thể được định nghĩa như là tích vô hướng các vector dòng của $A$ với $\boldsymbol{v}$
$$
A\boldsymbol{v} =
\begin{bmatrix}
  \langle \boldsymbol{a}_{1,}, \boldsymbol{v} \rangle \\
  \langle \boldsymbol{a}_{2,}, \boldsymbol{v} \rangle \\ \vdots \\
  \langle \boldsymbol{a}_{m,}, \boldsymbol{v} \rangle
\end{bmatrix},
$$
hay có thể được định nghĩa như là tổ hợp tuyến tính các vector cột của $A$ với các hệ số trong $\boldsymbol{v}$
$$
A\boldsymbol{v} =
v_1\begin{bmatrix}
  a_{11} \\ a_{21} \\ \vdots \\ a_{m1}
\end{bmatrix} +
v_2\begin{bmatrix}
  a_{12} \\ a_{22} \\ \vdots \\ a_{m2}
\end{bmatrix} + ... +
v_n\begin{bmatrix}
  a_{1n} \\ a_{2n} \\ \vdots \\ a_{mn}
\end{bmatrix} =
v_1\boldsymbol{a}_{,1} + v_2\boldsymbol{a}_{,2} + ... + v_n\boldsymbol{a}_{,n}.
$$

#### List

In [30]:
# The inner product of a row vector and a vector v
def mul_matrix_vector(A, v):
    return [calc_inner_product(ai, v) for ai in A]

# The linear combination of a column vector and a vector v
def mul_matrix_vector2(A, v):
    w = [0 for _ in range(len(v))]
    for j in range(len(v)):
        w = add_vector(w, mul_scalar_vector(v[j], [ai[j] for ai in A]))
    return w

In [31]:
A = [[1, 2, 3], [4, 5, 6]]
v = [1, 1, 1]

print('Matrix A: ')
myprint(A)
print('Vector v: ')
myprint(v)

print('Matrix-vector product Av, where A\'s rows are dot-producted with vector v')
print(mul_matrix_vector(A, v))

print('Matrix-vector product Av, where A\'s columns are linearly combined with the corresponding coefficients from vector v')
print(mul_matrix_vector2(A, v))

Matrix A: 
[[1 2 3]
 [4 5 6]]
Vector v: 
[1 1 1]
Matrix-vector product Av, where A's rows are dot-producted with vector v
[6, 15]
Matrix-vector product Av, where A's columns are linearly combined with the corresponding coefficients from vector v
[6, 15]


#### NumPy

In [32]:
A = np.array(A)
v = np.array(v)

print('Matrix A: ')
print(A)
print('Vector v: ')
print(v)

print('Av: ', np.matmul(A, v)) # NOTE: NOT A * v

Matrix A: 
[[1 2 3]
 [4 5 6]]
Vector v: 
[1 1 1]
Av:  [ 6 15]


#### SymPy

In [33]:
A = Matrix(A)
v = Matrix(sympy.symbols("alpha_1 alpha_2 alpha_3"))

A * v

⎡ α₁ + 2⋅α₂ + 3⋅α₃ ⎤
⎢                  ⎥
⎣4⋅α₁ + 5⋅α₂ + 6⋅α₃⎦

### Biến đổi sơ cấp trên dòng

3 loại biến đổi sau trên một ma trận được gọi là **phép biến đổi sơ cấp trên dòng** (elementary row operation):

- **Loại 1.** (Row switching) Đổi hai dòng cho nhau,

- **Loại 2.** (Row multiplication) Nhân một dòng với một số khác 0,

- **Loại 3.** (Row addition) Cộng vào một dòng một bội số của dòng khác.


Cho $A, B \in \mathbb{R}^{m \times n}$, ta nói $A, B$ **tương đương dòng** (row equivalent) với nhau nếu $B$ có được từ $A$ (hay ngược lại, $A$ có được từ $B$) qua hữu hạn phép biến đổi sơ cấp trên dòng.


Một ma trận được nói là có **dạng bậc thang theo dòng** (row echelon form) nếu:

- Các dòng khác $\boldsymbol{0}$ luôn nằm trên các dòng $\boldsymbol{0}$ (nếu có),

- Trên 2 dòng khác $\boldsymbol{0}$, hệ số khác 0 đầu tiên của dòng dưới luôn nằm bên phải cột chứa hệ số khác 0 đầu tiên của dòng trên.

#### List

In [34]:
def row_switch(A, i, k):
    'di <-> dk'
    A[i], A[k] = A[k], A[i]

def row_mul(A, i, alpha):
    'di = anpha*di'
    A[i] = mul_scalar_vector(alpha, A[i])

def row_add(A, i, k, alpha):
    'di = di + anpha*dk'
    A[i] = add_vector(A[i], mul_scalar_vector(alpha, A[k]))

def is_echelon(A): # Check if a matrix is echelon
    num_row, num_col = len(A) , len(A[0])
    prev_pivot_col = -1 

    for i in range(num_row):
        found_pivot = False  
        for j in range(num_col):
            if not is_zero(A[i][j]):
                if j <= prev_pivot_col:
                    return False
                for k in range(i+1,num_row):
                    if not is_zero(A[k][j]):
                        return False
                prev_pivot_col = j
                found_pivot = True
                break
            
        if not found_pivot:
            for k in range(j + 1, num_col):
                if not is_zero(A[i][k]):
                    return False  
    return True  


In [35]:
A = [[1, 2, 3],
     [4, 5, 6]]

print('Original matrix:')
myprint(A)

print('\nUpdate 0th row: d0 = 4d0')
row_mul(A, 0, 4)     # d0 = 4d0
myprint(A)

print('\nSwitch 0th and 1st rows: d0 <-> d1')
row_switch(A, 0, 1)  # d0 <-> d1
myprint(A)

print('\nUpdate 1st row: d1 = d1 - d0')
row_add(A, 1, 0, -1) # d1 = d1 - d0
myprint(A)

Original matrix:
[[1 2 3]
 [4 5 6]]

Update 0th row: d0 = 4d0
[[4 8 12]
 [4 5  6]]

Switch 0th and 1st rows: d0 <-> d1
[[4 5  6]
 [4 8 12]]

Update 1st row: d1 = d1 - d0
[[4 5 6]
 [0 3 6]]


#### SymPy

In [36]:
A = Matrix(A)

print(A.is_echelon)

True


In [37]:
A = A.elementary_row_op('n->n+km', row=1, row2=0, k=1)     # d1 = d1 + d0
A = A.elementary_row_op('n<->m', row1=1, row2=0)           # d1 <-> d0
A = A.elementary_row_op('n->kn', row=0, k=Fraction('1/4')) # d0 = d0/4


## Hệ PTTT và Phép khử Gauss <a class="anchor" id="c5"></a>

### Các khái niệm cơ bản

**Hệ PTTT** (system of linear equations, linear system) gồm $m$ phương trình theo $n$ ẩn số $x_1, x_2, ..., x_n$ là hệ có dạng
$$
\begin{matrix}
  a_{11}x_1 + a_{12}x_2 + ... + a_{1n}x_n = b_1 \\
  a_{21}x_1 + a_{22}x_2 + ... + a_{2n}x_n = b_2 \\
  \vdots \\
  a_{m1}x_1 + a_{m2}x_2 + ... + a_{mn}x_n = b_m \\
\end{matrix}.
$$

Hệ PTTT trên có thể được viết lại dưới dạng ma trận
$$ A\boldsymbol{x} = \boldsymbol{b} $$
với $A \in \mathbb{R}^{m \times n}$ là **ma trận các hệ số** (coefficient matrix)
$$
A =
\begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix},
$$
$\boldsymbol{x}$ là vector cột các **ẩn** (unknown) và $\boldsymbol{b}$ là vector cột các **hệ số vế phải** (right-hand side)
$$
\boldsymbol{x} =
\begin{bmatrix}
  x_{1} \\ x_{2} \\ \vdots \\ x_{n}
\end{bmatrix},
\boldsymbol{b} =
\begin{bmatrix}
  b_{1} \\ b_{2} \\ \vdots \\ b_{n}
\end{bmatrix}.
$$

Trường hợp $\boldsymbol{b} = \boldsymbol{0}$, hệ thường được gọi là hệ **thuần nhất** (homogeneous).

Với $A \in \mathbb{R}^{m \times n}, \boldsymbol{b} \in \mathbb{R}^{m \times 1}$ cho trước, ta nói $\boldsymbol{s} \in \mathbb{R}^{m \times 1}$ là vector **nghiệm** (solution) của hệ $A\boldsymbol{x} = \boldsymbol{b}$ nếu $A\boldsymbol{s} = \boldsymbol{b}$.

In [38]:
A = [[1, -1],
     [2, 1]]
b = [1, 6]

x = to_fraction(['7/3', '4/3'])

Ax = mul_matrix_vector(A, x)
myprint(Ax)

print('Is Ax == b?: ', equal_vector(Ax, b))

[1 6]
Is Ax == b?:  True


### Giải hệ PTTT

Hệ PTTT $A\boldsymbol{x} = \boldsymbol{b}$ thường được giải bằng các bước:

> **Bước 1.** Lập **ma trận bổ sung** (augmented matrix) bằng cách ghép cột $\boldsymbol{b}$ sau ma trận $A$: $\bar{A} = \left[ A | \boldsymbol{b} \right]$.

> **Bước 2.** Dùng các phép biến đổi sơ cấp trên dòng để biến đổi $\bar{A}$ thành ma trận tương đương dòng có dạng bậc thang $R$.

> **Bước 3.** Giải $R$ bằng **phép thế ngược** (back-substitution) để có nghiệm.

***Mệnh đề.*** Nếu $\bar{A}, \bar{B}$ tương đương dòng thì các hệ PTTT tương ứng với ma trận bổ sung $\bar{A}, \bar{B}$ có cùng tập nghiệm.

#### Bước 1: Lập ma trận bổ sung

In [39]:
def augmented_matrix(A, b):
    'Create the augmented matrix [A|b]'
    return [ai + [bi] for ai, bi in zip(A, b)] # Quick question: What does this code mean: ai + [bi]?

A_bar = augmented_matrix(A, b)

myprint(A_bar)

[[1 -1 1]
 [2  1 6]]


#### Bước 2: Tạo ma trận bậc thang - Sử dụng phép khử Gauss

**Khử Gauss** (Gaussian elimination) là một cách biến đổi tương đương dòng đưa ma trận về dạng bậc thang. Thuật giải gồm các bước:

> **Bước 1.** Xác định cột trái nhất không chứa toàn số 0.

> **Bước 2.** Đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới về đầu cột nhận được ở Bước 1.   
(*Đơn giản nhất, có thể chọn dòng đầu tiên có số hạng khác 0. Phức tạp hơn, chiến lược "partial pivoting" chọn dòng có số hạng có trị tuyệt đối lớn nhất.*)

> **Bước 3.** Với số hạng đầu cột nhận được từ Bước 2 là $a \neq 0$, nhân dòng chứa nó với $\frac{1}{a}$ để có **số dẫn đầu** 1 (leading 1).  
(*Bước này tùy chọn*.)

> **Bước 4.** Cộng một bội số thích hợp của dòng đầu cho từng dòng dưới để biến các số hạng bên dưới số dẫn đầu thành 0.

> **Bước 5.** Che dòng đầu đã làm xong. Lặp lại các bước cho đến khi được ma trận bậc thang.

In [40]:
def Gauss_elimination(A, leading1):
    # WRITE YOUR CODE HERE
    m, n =len(A), len(A[0])

    #Step1: Check if the leftmost column contains all zeros
    def is_column_zero(col_index):
        i = col_index
        for i in range(m):
            if not is_zero(A[i][col_index]):
                return False
        return True

    def is_sub_column_zero(col_index, row_index):
        for i in range(row_index, m):
            if A[i][col_index] !=0:
                return False
        return True
        
    #Step2: Swap rows if it !=0;
    def swap_rows(row_index):
        for i in range (row_index + 1,m):
            if not is_zero(A[i][row_index]) and is_one(A[i][row_index]):
                temp = A[row_index]
                A[row_index] = A[i]
                A[i] = temp
                break

    def swap_rows_3(row_index, col_index):
        best_row = row_index
        best_col = n  

        for i in range(row_index + 1, m):
            for j in range(col_index, n):
                if not is_zero(A[i][j]) and j < best_col:
                    best_row = i
                    best_col = j
                    break

        if best_row != row_index:
            temp_row = A[row_index]
            A[row_index] = A[best_row]
            A[best_row] = temp_row
                
    #Step3: Make leading 1:
    def make_leading_one(row_index, col_index=None):
        if col_index is None:
            col_index = row_index
        leading_coefficient = A[row_index][col_index]
        if leading_coefficient != 0 and not is_one(leading_coefficient):
            scale_factor = 1 / leading_coefficient
            A[row_index] = [element * scale_factor for element in A[row_index]]

    #Step4: Make elements below leading term zero
    def eliminate_below(row_index, col_index=None):
        if col_index is None:
            col_index = row_index
        for i in range(row_index + 1, m):
            if not is_zero(A[row_index][col_index]):
                factor = A[i][col_index] / A[row_index][col_index]
                A[i] = [A[i][j] - factor * A[row_index][j] for j in range(n)]

    #step5: Main loop for Gauss Elimination
    for i in range(min(m, n)):
        if not is_column_zero(i) and not is_sub_column_zero(i,i):
            swap_rows(i)
            if leading1:
                make_leading_one(i)
            eliminate_below(i)
        elif is_sub_column_zero(i,i) :
            if i+1<n and not is_sub_column_zero(i+1,i):
                swap_rows(i - 1)
                if leading1:
                    make_leading_one(i, i+1)
                eliminate_below(i, i+1)
            elif i+1<n and is_sub_column_zero(i+1,i):
                next_column = i + 1
                while next_column<n and is_sub_column_zero(next_column, i) :
                    next_column += 1

                if i+next_column-2<n:
                    swap_rows_3(i,i+next_column-2)
                    if leading1:
                        make_leading_one(i, i+next_column-2)
                    eliminate_below(i, i+next_column-2)

    return A

In [41]:
A = [[1, 3, -2,  0, 2,  0, 0],
     [2, 6, -5, -2, 4, -3, 0],
     [0, 0,  5, 10, 0, 15, 0],
     [2, 6,  0,  8, 4, 18, 0]]

print('Matrix before transforming into row echelon form (REF):')
myprint(A)

print('\nMatrix after transforming into REF (with leading 1):')
myprint(Gauss_elimination(to_fraction(A), True))

print('\nMatrix after transforming into REF (without leading 1):')
myprint(Gauss_elimination(to_fraction(A), False))


Matrix before transforming into row echelon form (REF):
[[1 3 -2  0 2  0 0]
 [2 6 -5 -2 4 -3 0]
 [0 0  5 10 0 15 0]
 [2 6  0  8 4 18 0]]

Matrix after transforming into REF (with leading 1):
[[1 3 -2 0 2 0 0]
 [0 0  1 2 0 3 0]
 [0 0  0 0 0 1 0]
 [0 0  0 0 0 0 0]]

Matrix after transforming into REF (without leading 1):
[[1 3 -2  0 2  0 0]
 [0 0 -1 -2 0 -3 0]
 [0 0  0  0 0  6 0]
 [0 0  0  0 0  0 0]]


#### Bước 3: Phép thế ngược

In [42]:
def back_substitution(R):
    
    # Function to count the number of zero vectors needed
    def count_zero_vectors_needed(R):
        num_rows = len(R)
        num_cols = len(R[0])
        return max(0, num_cols - 1 - num_rows)
    
    # Function to add zero vectors if needed
    def add_zero_vectors(R):
        num_cols = len(R[0])
        num_zero_vectors_needed = count_zero_vectors_needed(R)
        
        if num_zero_vectors_needed == 0:
            return R
        
        # Add zero vectors
        R2 = [row[:] for row in R]  # Copy R to R2
        for _ in range(num_zero_vectors_needed):
            zero_vector = [0] * num_cols
            R2.append(zero_vector)
        
        return R2
    
    # Count zero vectors needed and add them if necessary
    R = add_zero_vectors(R)
    m, n = len(R), len(R[0])
    solutions = [None] * (n - 1)

    for i in range(m - 1, -1, -1):
        row = R[i]
        
        # Check if the row has all zeroes except the last element
        if all(is_zero(row[j]) for j in range(n - 1)):
            if not is_zero(row[-1]):
                return "No solution."
            # Assign free variable
            free_var = None
            for j in range(n - 1):
                if solutions[j] is None:
                    free_var = j
                    break
            if free_var is not None:
                solutions[free_var] = f"x{free_var + 1}"
        
        # Find the pivot column
        pivot_col = None
        for j in range(n - 1):
            if not is_zero(row[j]):
                pivot_col = j
                break
        
        if pivot_col is not None:
            rhs = row[-1]
            equation = []
            for j in range(pivot_col + 1, n - 1):
                if not is_zero(row[j]):
                    if solutions[j] is not None:
                        if isinstance(solutions[j], (int, float, Fraction)):
                            rhs -= row[j] * solutions[j]
                        else:
                            equation.append(f"({-row[j]})*{solutions[j]}")
                    else:
                        equation.append(f"({-row[j]})*x{j+1}")
            if equation:
                equation_str = " - ".join(equation)
                solutions[pivot_col] = f"{rhs} - {equation_str}"
            else:
                solutions[pivot_col] = rhs / row[pivot_col]
        else:
            free_var = None
            for j in range(n - 1):
                if solutions[j] is None:
                    free_var = j
                    break
            if free_var is not None:
                solutions[free_var] = f"x{free_var + 1}"

    # Convert solutions to string
    def clean_solution(sol):
        if isinstance(sol, str):
            terms = sol.split(" - ")
            cleaned_terms = [term for term in terms if not any(is_zero(float(f)) for f in term.split('*') if f.replace('.', '', 1).isdigit())]
            return " - ".join(cleaned_terms)
        return str(sol)

    solutions_str = [clean_solution(sol) if sol is not None else "0" for sol in solutions]
    
    return solutions_str

In [43]:
A = [[1, 3, -2,  0, 2,  0, 0],
     [2, 6, -5, -2, 4, -3, 0],
     [0, 0,  5, 10, 0, 15, 0],
     [2, 6,  0,  8, 4, 18, 0]]

solutions = back_substitution(Gauss_elimination(to_fraction(A), True))
print(f"Solution:")
print(", ".join(solutions))

Solution:
(-3)*x2 - (-2)*x4 - (-2)*x5, x2, (-2)*x4, x4, x5, 0


#### Quy định bài nộp
> Thực hiện toàn bộ bài làm trên 1 tập tin Jupiter Notebook (.ipynb) hoặc Python (.py)

> Nộp tập tin dưới dạng MSSV.zip được nén từ thư mục MSSV chứa các tập tin sau:

- Báo cáo toàn bộ bài làm: MSSV.pdf

- Mã nguồn: MSSV.ipynb hoặc MSSV.py

> Trong đó, nội dung tập tin báo cáo gồm có:

- Thông tin cá nhân: họ và tên, MSSV

- Ý tưởng thực hiện, mô tả các hàm




#### Quy định chấm bài

Những trường hợp sau đây sẽ bị 0 điểm toàn bộ đồ án:

- Nộp sai quy định

- Không có báo cáo

- Thực thi mã nguồn báo lỗi

**Lưu ý: Sao chép bài làm của nhau sẽ bị 0 điểm toàn bộ phần thực hành **